spring.application.name=gemini-chat

# Gemini API
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent
gemini.embedding.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent
gemini.batch.embedding.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:batchEmbedContents

# Pinecone
pinecone.api.key=${PINECONE_API_KEY}
pinecone.host=${PINECONE_HOST}
